### ISSUE TITLE
using provided example creates a non fully functional cluster

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#290]
i deployed the following manifests
- https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/examples/securityconfig-secret.yaml
- https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/examples/opensearch-cluster-securityconfig.yaml  

then i upgraded opensearch to version 2.1.1 by only changing the version.

all my data indexes are yellow with the following reasons

```
{
  "index" : "network-2022.09.08",
  "shard" : 0,
  "primary" : false,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "INDEX_CREATED",
    "at" : "2022-09-08T00:00:01.224Z",
    "last_allocation_status" : "no_attempt"
  },
  "can_allocate" : "no",
  "allocate_explanation" : "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions" : [
    {
      "node_id" : "G2IYImMUSnuWO-c5agBa4w",
      "node_name" : "secure-cluster-masters-2",
      "transport_address" : "10.244.4.62:9300",
      "node_attributes" : {
        "shard_indexing_pressure_enabled" : "true"
      },
      "node_decision" : "no",
      "weight_ranking" : 1,
      "deciders" : [
        {
          "decider" : "enable",
          "decision" : "NO",
          "explanation" : "replica allocations are forbidden due to cluster setting [cluster.routing.allocation.enable=primaries]"
        }
      ]
    },
```

the expectation, is of course, is to have a green cluster

**Comment by segalziv** [comment]
Right, thanks for reporting this @anubisg1 . I was able to reproduce it. 
@prudhvigodithi it looks like on some conditions when upgrading to 2.x the upgrade succeed but it doesn't remove the restrictions of cluster.routing.allocation.enable=primaries

**Comment by idanl21** [comment]
Fixed

**Comment by anubisg1** [comment]
i still see a similar issue with 2.1.1 and clusters on 2.x. every time i make a change that restarts nodes i endup with allocation problems which i can only fix by manually running

```
PUT _cluster/settings
{
  "transient": {
 	"cluster.routing.allocation.enable": "all"
  }
}
```
