### ISSUE TITLE
Cluster stuck in yellow state after the rolling restart

### ISSUE THREAD

**Issue by ervikrant06** [Opster/opensearch-k8s-operator#400]
Create a new cluster, make any change to additionalconfig or any attribute which can cause the rolling restart of whole cluster. Cluster during the rolling restart prob set the allocation only for primaries but it's not able to clear the state to "all" from only "primaries" after completing the rolling restart because of which cluster stays in "yellow" state. I am able to reproduce the issue. 

~~~
{
  "persistent" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "all"
        }
      }
    },
    "plugins" : {
      "index_state_management" : {
        "template_migration" : {
          "control" : "-1"
        }
      }
    }
  },
  "transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "primaries"
        }
      }
    }
  }
}
~~~

Solution:

Manually change the cluster setting to "all" to bring the cluster in healthy state.

**Comment by idanl21** [comment]
Hey @ervikrant06, i will try to reproduce the issue in my cluster, im familiar with that bug, but i thought that we already fixed it.
which version of the Operator are you running ?

**Comment by ervikrant06** [comment]
Hello @idanl21 I am using opensearch version 2.3.0, Operator image I built through master 1-2 weeks ago.

**Comment by anubisg1** [comment]
I commented a while back and I can confirm that the bug isn't fixed. I get the same error everytime there is a cluster change not just a rolling upgrade.

**Comment by balpert89** [comment]
I can confirm as well, bug is still existing in current master.

https://github.com/Opster/opensearch-k8s-operator/issues/293 also describes the issue, it may makes sense to consolidate the issues.

**Comment by swoehrl-mw** [comment]
Took a look at this and I think I found the problem: When a rolling restart is finished, the restart reonciler has currently no way to detect that a rolling restart was in progress and that it should reenable shard allocation.
Created PR #406 for it. Second opinions would be welcome.

**Comment by swoehrl-mw** [comment]
We just released version 2.2.1 which contains the fix for this bug.
