### ISSUE TITLE
Cluster fail after deleting and recreating it. 

### ISSUE THREAD

**Issue by mohammadzahid525** [Opster/opensearch-k8s-operator#419]
I created a cluster with version 2.5.0 and everything worked fine. 
I deleted the cluster and tried recreating it, it got stuck and dashboard pods throws error. 
The only way to solve this is deleting the pvc that were created earlier and recreating cluster, but this also deletes all the existing indices and dashboard objects I have since it will create a new pvc and pv. 
In elastic search it doesn't work like this, it easily get attach to existing volumes if I recreate cluster. 
Any help is appreciated.

**Comment by swoehrl-mw** [comment]
Hi @mohammadzahid525. This is a current known issue with the cluster bootstrap process the operator follows. With PR #366 this will hopefully be possible. 
The workaround from https://github.com/Opster/opensearch-k8s-operator/issues/266#issuecomment-1268499249 could also work here.

**Comment by anubisg1** [comment]
just in case someone gets lost with what's needed, those are the steps needed.
This is assuming that you only have node type masters and nodes, and that the cluster is called "opensearch-cluster".
Please make sure you use the right statefulset names 


# Cluster Recovery #

The following instructions will help you recover the cluster if we end up in the situation described here:
https://github.com/Opster/opensearch-k8s-operator/issues/289

1. scale down and backup
```
kubectl scale deployment opensearch-operator-controller-manager --replicas=0 -n opensearch-operator
kubectl get statefulset opensearch-cluster-masters -n opensearch -o yaml > masters.yaml
kubectl get statefulset opensearch-cluster-nodes -n opensearch -o yaml > nodes.yaml

kubectl delete statefulset opensearch-cluster-masters --cascade=orphan -n opensearch
kubectl delete statefulset opensearch-cluster-nodes --cascade=orphan -n opensearch
```

2. change `podManagementPolicy` from `OrderedReady` to `Parallel` and apply
```
vim masters.yaml 
vim nodes.yaml

kubectl apply -f masters.yaml 
kubectl apply -f nodes.yaml
```

3. verify cluster recovered then restore the operator
```
kubectl delete statefulset opensearch-cluster-masters --cascade=orphan -n opensearch
kubectl delete statefulset opensearch-cluster-nodes --cascade=orphan -n opensearch
```

4. change `podManagementPolicy` from `Parallel` to `OrderedReady` and apply
```
vim masters.yaml 
vim nodes.yaml 

kubectl apply -f masters.yaml 
kubectl apply -f nodes.yaml 
kubectl scale deployment opensearch-operator-controller-manager --replicas=1 -n opensearch-operator
```

**Comment by swoehrl-mw** [comment]
Hi @mohammadzahid525. PR #366 was merged and is part of version 2.2.1. With that fix your problem should be resolved.
Closing this issue.

**Comment by wbrown-ping** [comment]
I am still seeing this issue on version 2.11.1.  Any thoughts?

**Comment by swoehrl-mw** [comment]
Hi @wbrown-ping. The opensearch version (in your case 2.11.1 is not relevant), the operator version is relevant. Do you have the latest (2.6.1) there?

**Comment by wbrown-ping** [comment]
Hi @swoehrl-mw , no.  I am on operator 2.5.1.  You'd recommend upgrading?

**Comment by swoehrl-mw** [comment]
@wbrown-ping Yes, and also make sure `manager.parallelRecoveryEnabled` in the operator helm chart values is not accidentially disabled.

**Comment by berginv** [comment]
Hi @swoehrl-mw Im using Opensearch version `2.9.0` and Opensearch Operator version `2.7.0` . I'm facing the same issue..
